### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [ ]:
#1                                                                  
pari = []                                                                  
for n in range(20):                                                           
    if n % 2 == 0: 
        pari.append(n)
                                                                                
pari = [n for n in range(20) if n % 2 == 0]  
print(pari)                                 
                                                                             
#2                                                                   
quadrati = []                                                              
for n in [1, 2, 3, 4, 5]:
    quadrati.append(n ** 2)
                                                                                
 
quadrati = [n ** 2 for n in [1, 2, 3, 4, 5]]    
print(quadrati)                              
                                                                             

#3
iniziali = []                                                                 
for nome in ["alice", "bruno", "Carla"]:                                   
    iniziali.append(nome[0].upper())                                          
                                                                             
                                                          
iniziali = [nome[0].upper() for nome in ["Alice", "Bruno", "Carla"]]
print(iniziali)
                                    

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[1, 4, 9, 16, 25]
['A', 'B', 'C']


### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [ ]:
import numpy as np

def isprime(x):
    for i in range(2,x-1):
        if x % i == 0:
            return False
    return True

primi=np.array([i for i in range(2,10) if isprime(i)])
print(len(primi))
print(primi.size)
print(primi.dtype)
primi



4
4
int64


array([2, 3, 5, 7])

### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [ ]:
import numpy as np
a=np.arange(1,20)
b=a[2:4]
c=a[::-1]
a,b,c

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19]),
 array([3, 4]),
 array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
         2,  1]))